import { Inter } from "next/font/google"
import { NextAuthProvider } from "@/contexts"
import "./globals.sass"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "GenPost",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <body className={inter.className}>
          <NextAuthProvider>
            {children}
          </NextAuthProvider>  
        </body>
      </html>
  )
}
